/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.Timer;

/**
 *
 * @author budi
 */
public class LaluLintas2 extends javax.swing.JFrame {
    String pesan;
    int portSend = 5000;
    int portReceive = 4400;
    String ipPublic = "localhost";
    boolean calling = true;
    
    public LaluLintas2() {
        initComponents();
        Controller con =  new Controller();
        con.start();
    }
    
     public class Controller extends Thread{
        @Override
        public void run() {
            while (calling) {            
                receiveData();
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        LampuMerah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LampuKuning = new javax.swing.JButton();
        LampuHijau = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        btnMerah = new javax.swing.JButton();
        btnKuning = new javax.swing.JButton();
        btnHijau = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LampuMerah.setIcon(new javax.swing.ImageIcon("/media/budi/Dell_Data1/Documents/PemrogramanJaringan/UDP/buttonMerah.png")); // NOI18N

        jLabel1.setText("Traffic 2");

        LampuKuning.setIcon(new javax.swing.ImageIcon("/media/budi/Dell_Data1/Documents/PemrogramanJaringan/UDP/buttonKuning.png")); // NOI18N

        LampuHijau.setIcon(new javax.swing.ImageIcon("/media/budi/Dell_Data1/Documents/PemrogramanJaringan/UDP/buttonHijau.png")); // NOI18N

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        btnMerah.setText("Merah");
        btnMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerahActionPerformed(evt);
            }
        });

        btnKuning.setText("Kuning");
        btnKuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuningActionPerformed(evt);
            }
        });

        btnHijau.setText("Hijau");
        btnHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKuning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMerah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LampuMerah)
                            .addComponent(LampuKuning))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHijau, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LampuHijau)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Exit)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LampuMerah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LampuKuning))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMerah)
                        .addGap(91, 91, 91)
                        .addComponent(btnKuning)
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LampuHijau))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnHijau)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        calling = false;
        try{
            InetAddress ip = InetAddress.getByName(ipPublic);
            pesan = "stop";
            byte[] data = pesan.getBytes();
            DatagramPacket dp = new DatagramPacket(data, data.length, ip, portSend);
            DatagramSocket sender = new DatagramSocket();
            sender.send(dp);
            sender.close();
            System.out.println("pesan = " + pesan);
        }
        catch(Exception e){
            System.out.println(e);
        }
        System.exit(0);
        calling = true;
    }//GEN-LAST:event_ExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void btnMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerahActionPerformed
        calling = false;
        try{
            InetAddress ip = InetAddress.getByName(ipPublic);
            pesan = "merah";
            byte[] data = pesan.getBytes();
            DatagramPacket dp = new DatagramPacket(data, data.length, ip, portSend);
            DatagramSocket sender = new DatagramSocket();
            sender.send(dp);
            sender.close();
            System.out.println("pesan = " + pesan);
        }
        catch(Exception e){
            System.out.println(e);
        }
        calling = true;
    }//GEN-LAST:event_btnMerahActionPerformed

    private void btnKuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuningActionPerformed
        calling = false;
        try{
            InetAddress ip = InetAddress.getByName(ipPublic);
            pesan = "kuning";
            byte[] data = pesan.getBytes();
            DatagramPacket dp = new DatagramPacket(data, data.length, ip, portSend);
            DatagramSocket sender = new DatagramSocket();
            sender.send(dp);
            sender.close();
            System.out.println("pesan = " + pesan);
        }
        catch(Exception e){
            System.out.println(e);
        }
        calling = true;
    }//GEN-LAST:event_btnKuningActionPerformed

    private void btnHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijauActionPerformed
        calling = false;
        try{
            InetAddress ip = InetAddress.getByName(ipPublic);
            pesan = "hijau";
            byte[] data = pesan.getBytes();
            DatagramPacket dp = new DatagramPacket(data, data.length, ip, portSend);
            DatagramSocket sender = new DatagramSocket();
            sender.send(dp);
            sender.close();
            System.out.println("pesan = " + pesan);
        }
        catch(Exception e){
            System.out.println(e);
        }
        calling = true;
    }//GEN-LAST:event_btnHijauActionPerformed
    
    public void receiveData(){
        try {
            byte[] buffer = new byte[656];
            DatagramPacket incoming = new DatagramPacket(buffer, buffer.length);
            DatagramSocket ds = new DatagramSocket(portReceive);
            ds.receive(incoming);
            byte[] data = incoming.getData();
            pesan = new String(data, 0, data.length);
            System.out.println("pesan = " + pesan);

            pesan=pesan.trim();

            switch(pesan){
                case "merah":
                    LampuMerah.setEnabled(true);
                    LampuKuning.setEnabled(false);
                    LampuHijau.setEnabled(false);
                    break;
                case "kuning":
                    LampuMerah.setEnabled(false);
                    LampuKuning.setEnabled(true);
                    LampuHijau.setEnabled(false);
                    break;
                case "hijau":
                    LampuMerah.setEnabled(false);
                    LampuKuning.setEnabled(false);
                    LampuHijau.setEnabled(true);
                    break;
                case "stop":
                    System.exit(0);
                    break;
            }
            ds.close();
        }catch (IOException e) {
            System.err.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaluLintas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaluLintas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaluLintas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaluLintas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaluLintas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton LampuHijau;
    private javax.swing.JButton LampuKuning;
    private javax.swing.JButton LampuMerah;
    private javax.swing.JButton btnHijau;
    private javax.swing.JButton btnKuning;
    private javax.swing.JButton btnMerah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
